# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc64f07d185c785cf6f4cbc1806081eb40b9e9b07bf35ffdf497cdf3f71ee57805d0cbe7506c314c3fbc73c326a1ceb385916a38d617ad742f513ced13c1f7c8

test:
  secret_key_base: ca23eb8b6c3d43297ce55a12fb86b77cc465d7e20da544e66eb2e1946eabbf472cacc22c700bd087f4016cadc05dc0d44102cef03bf4af821cdcc4ad8fc0d572

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
